# Generated by Django 4.0.4 on 2022-04-28 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('SHA', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='Blob')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 11, 48, 10, 70154))),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('SHA', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FileList.blob')),
            ],
        ),
        migrations.CreateModel(
            name='TreeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tree', to='FileList.tree')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tree', to='FileList.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('work_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_branch', to='FileList.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('child_num', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FileList.commit')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileList.tree')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FileList.commit'),
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileList.store'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique name of each store'),
        ),
    ]
