# Generated by Django 4.0.4 on 2022-04-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileList', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
